# Use root/example as user/password credentials
version: '4.4'
services:
  mongo:
    container_name: mongo
    image: mongo
    hostname: mongo
    networks:
      mynet:
        aliases:
          - dbmongo.airtree
    restart: always
    volumes:
      - type: bind
        source: /data
        target: /data/db
    expose:
      - 27017:27017
    ports:
      - 127.0.0.1:27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${mongo_user}
      MONGO_INITDB_ROOT_PASSWORD: ${mongo_pass}
    logging:
      options:
        max-size: "10m"
        max-file: "2"

  mongo-express:
    container_name: mongo_express
    networks:
      mynet:
    image: mongo-express
    restart: always
    ports:
      - 127.0.0.1:8081:8081
    expose:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${mongo_user}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${mongo_pass}
      ME_CONFIG_MONGODB_URL: mongodb://${mongo_user}:${mongo_pass}@mongo:27017/
    logging:
      options:
        max-size: "10m"
        max-file: "2"

  airtree-server:
    build: docker_flask/
    restart: always
    networks:
      mynet:
    ports:
        - 433:433
        - 5000:5000
    logging:
      options:
        max-size: "10m"
        max-file: "2"

  airtree-worker:
    container_name: airtree-worker
    restart: always
    networks:
      mynet:
    build: docker_worker/
    logging:
      options:
        max-size: "10m"
        max-file: "2"

networks:
  mynet:
